### ISSUE TITLE
loss concussion

### ISSUE THREAD

**Issue by gk616828144** [unsky/FPN#16]
Hi, I add the fpn to ZF and i train the pasalvoc datasets. The loss  is  high, can you give me some advice?
ps: I just add two feature pyramid layer p4，p3 to ZF

**Comment by unsky** [comment]
i have update codes

**Comment by happygao** [comment]
@unsky  hello, unsky, I am trying do the experiments by my own dataset, (the dataset is eight classes)but it occurs the error.But when I use the voc data, it not produce the error. I want to know what reason causes the error?

**Comment by happygao** [comment]
I change the pascal_voc/train.prototxt/num classes 21 to 8, the 84 to 32, it occurs the above error.

**Comment by unsky** [comment]
layer {
  name: 'roi-data'
  type: 'Python'
  bottom: 'rpn_rois'
  bottom: 'gt_boxes'
  top: 'rois/h2'
  top: 'rois/h3'
  top: 'rois/h4'
  top: 'rois/h5'
  top: 'labels'
  top: 'bbox_targets'
  top: 'bbox_inside_weights'
  top: 'bbox_outside_weights'
  python_param {
    module: 'rpn.proposal_target_layer'
    layer: 'ProposalTargetLayer'
    param_str: "'num_classes': 21"
  }
}
change ProposalTargetLayer param_str: "'num_classes': 21" to your class num

**Comment by happygao** [comment]
Thanks very much. I have changed the num_classes to my class num. The error has not changed. Could you add me, QQ:1119105525, I want to ask you some questions,please.

**Comment by foralliance** [comment]
@happygao 
i meet the same problem.
have u solved the problem?? many many thanks
