### ISSUE TITLE
rpn_cls_score/p2 output参数不一致

### ISSUE THREAD

**Issue by 462662927** [unsky/FPN#20]
rpn_cls_score/p2这个layer在trian.prototxt和test.prototxt，output参数不一致

**Comment by unsky** [comment]
@462662927  再仔细看下实现逻辑吧，cls_score那几个reshape是为了在训练阶段同时可以concat并且可以对应原feature map的位置映射，train 和test只有shape的区别，目前我训练了6W次mAP77.9（@0.5），再训练一些次数应该能达到79+，出了最新结果会更新results..
