### ISSUE TITLE
各个rpn中的anchor问题

### ISSUE THREAD

**Issue by zhDai** [unsky/FPN#24]
unsky，你好!我在查看rpn网络的时候，发现这五个rpn模块用的都是相同的achor大小，而不是原论文中的那种说法。你是否尝试过每个level只对应一个固定且不同的anchor大小？

**Comment by unsky** [comment]
建议换个姿势再好好查看。。。

**Comment by zhDai** [comment]
那你是有30种anchor？（5*2*3）

**Comment by unsky** [comment]
嗯，看readme

**Comment by zhDai** [comment]
好的，谢谢
