### ISSUE TITLE
loss=nan

### ISSUE THREAD

**Issue by LeonJWH** [unsky/FPN#27]
I add your **rpn operator** to my caffe to train **fpn**, I set batch_size as 2, base_lr to 0.0001 to 0.001, the loss reduce from larger than 3 to smaller than 1 after hundreds of iterations, then the loss became to Nan. Can you give me some advises? And serveral warnings occured during training progress, shown as below.
 
![2018-01-13 8 54 37 2](https://user-images.githubusercontent.com/17867054/34906667-d04e60f6-f8ac-11e7-8944-6b535acd670b.png)
![2018-01-13 9 43 45](https://user-images.githubusercontent.com/17867054/34906670-daf101d0-f8ac-11e7-9d03-92ac47b330a6.png)

**Comment by unsky** [comment]
lr and anchor size is based on the datasets, Nan will occured if lr is too big.
ps: FPN， faster rcnn dont support multi-batch size, i cant understand your batch size =2.

**Comment by LeonJWH** [comment]
i use 2 gpu to train发自我的华为手机-------- 原始邮件 --------主题：Re: [unsky/FPN] loss=nan (#27)发件人：unsky 收件人：unsky/FPN 抄送：Garvin ,Author lr and anchor size is based on the datasets, Nan will occured if lr is too big.
ps: FPN， faster rcnn dont support multi-batch size, i cant understand your batch size =2.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/unsky/FPN","title":"unsky/FPN","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/unsky/FPN"}},"updates":{"snippets":[{"icon":"PERSON","message":"@unsky in #27: lr and anchor size is based on the datasets, Nan will occured if lr is too big.\r\nps: FPN， faster rcnn dont support multi-batch size, i cant understand your batch size =2. "}],"action":{"name":"View Issue","url":"https://github.com/unsky/FPN/issues/27#issuecomment-357437904"}}}

**Comment by LeonJWH** [comment]
i use 2 gpu to train

**Comment by unsky** [comment]
reduce lr to get a suit one
