### ISSUE TITLE
anchor_size

### ISSUE THREAD

**Issue by foralliance** [unsky/FPN#31]
FPN是一个多层预测框架，每一个分支都要设置对应的anchors．那么在不同层设置anchors，设计原则是什么？
还有您README中的about the anchor size setting一部分，能不能解释一下．
麻烦了！！

**Comment by unsky** [comment]
是根据数据集里物体的尺寸设计的，比如voc的尺寸大多在128 256 512，而coco里有很多32 64尺寸的物体，所以需要设计不同的尺寸，最合理的方法是先对数据集里物体大小统计分析，然后设计合适的尺寸，比如如果使用论文对coco的设置会导致p2层基本没用，rpn的recall能力会变的非常差。

**Comment by twmht** [comment]
@unsky 

請問你指的尺寸是指物件大小？比如 128 的話就是 128 X 128?
