### ISSUE TITLE
单张1080ti上跑训练会报out of memory错误

### ISSUE THREAD

**Issue by zg9uagfv** [unsky/FPN#42]
单张1080ti上跑训练会报错误：
 syncedmem.cpp:56] Check failed: error == cudaSuccess (2 vs. 0)  out of memory

我在solver文件把iter_size改为1，还是报一样的错。

是显存的不够的原因吗？

**Comment by unsky** [comment]
大概需要10g多一些，此外iter-size不影响显存单卡，在config.py里可以修改相关参数

**Comment by evanfly** [comment]
把__C.TRAIN.MAX_SIZE改小，可以把显存降下来，我的1070 8g就可以训练

**Comment by zg9uagfv** [comment]
谢谢  @unsky @evanfly
