### ISSUE TITLE
代码细节询问

### ISSUE THREAD

**Issue by Huangswust182** [unsky/FPN#43]
在源码的RPN中proposal_target_layer.py里
    if sample_type == 'fpn':
        #print 0
        w = (rois[:,3]-rois[:,1])
        h = (rois[:,4]-rois[:,2])
        s = w * h
        s[s<=0]=1e-6
        layer_index = np.floor(k0+np.log2(np.sqrt(s)/224))

        layer_index[layer_index<2]=2
        layer_index[layer_index>5]=5
这部分中的layer_index是怎样计算的呀？有些许不懂，希望有人能够解答，非常感谢

**Comment by unsky** [comment]
读paper

**Comment by Huangswust182** [comment]
@unsky 
好吧，谢谢

**Comment by Huangswust182** [comment]
@unsky 
再问一下，index = (layer_indexs == (i + 2))这里为什么加了个2啊？是上采样嘛？
