### ISSUE TITLE
Only one GPU?

### ISSUE THREAD

**Issue by ouchjm** [unsky/FPN#54]
training can only use one gpu? 
if i have two gpus, how modify it? 
thank you~

**Comment by ouchjm** [comment]
can't use multi-gpu training: makes heavy use of python layers and python layers break the multi-gpu feature, thank you.

**Comment by foralliance** [comment]
@ouchjm 
How to understand "can't use multi-gpu training: makes heavy use of python layers and python layers break the multi-gpu feature"
